name: List Merged PRs

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      since:
        description: "ISO 8601 datetime to list merged PRs since (e.g. 2025-08-13T00:00:00Z). Leave blank to use Aug 13, 2025 00:00 UTC."
        required: false
        default: '2025-08-13T00:00:00Z'

jobs:
  list-merged-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh jq

      - name: Generate merged PR list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          REPOS=(
            "wso2/product-is"
            "wso2/identity-apps"
            "wso2/identity-api-server"
            "wso2/identity-api-user"
            "wso2/carbon-identity-framework"
            "wso2/identity-organization-management-core"
            "wso2-extensions/identity-governance"
            "wso2-extensions/identity-organization-management"
            "wso2/carbon-kernel"
            "wso2-extensions/identity-inbound-provisioning-scim2"
            "wso2-extensions/identity-inbound-auth-oauth"
            "wso2-extensions/identity-webhook-event-handlers"
            "wso2-extensions/identity-event-publishers"
          )

          if [ -n "${{ github.event.inputs.since }}" ]; then
            SINCE="${{ github.event.inputs.since }}"
          else
            SINCE="2025-08-13T00:00:00Z"
          fi

          echo "# Merged PRs since $SINCE" > merged_prs.md
          for repo in "${REPOS[@]}"; do
            echo "## $repo" >> merged_prs.md
            gh pr list \
              --repo "$repo" \
              --state merged \
              --search "merged:>=$SINCE" \
              --json number,title,author,mergedAt,url \
              --jq '.[] | "- [#\(.number)](\(.url)) \(.title) — @\(.author.login) (\(.mergedAt))"' >> merged_prs.md
            echo "" >> merged_prs.md
          done

      - name: Commit and push PR list
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add merged_prs.md
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "chore: update merged PR list [skip ci]"
          git push https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:${GITHUB_REF#refs/heads/}
